/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import javax.swing.JTextArea;
import controladores.*;
/**
 *
 * @author randysmc
 */
public class VentanaEditor extends javax.swing.JFrame {
    ControladorSintactico controladorSintactico;

    /**
     * Creates new form ventanaEditor
     */
    public VentanaEditor() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEditor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmGuardar = new javax.swing.JMenu();
        jmGuardarComo = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jmMostrarTexto = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editor Texto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N

        textAreaEditor.setEditable(false);
        textAreaEditor.setColumns(20);
        textAreaEditor.setRows(5);
        jScrollPane1.setViewportView(textAreaEditor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
        );

        jmGuardar.setText("Guardar");
        jMenuBar1.add(jmGuardar);

        jmGuardarComo.setBackground(new java.awt.Color(0, 51, 51));
        jmGuardarComo.setForeground(new java.awt.Color(0, 51, 51));
        jmGuardarComo.setText("Guardar Como");
        jMenuBar1.add(jmGuardarComo);

        jMenu4.setText("Editar");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jmMostrarTexto.setText("Mostrar Texto");
        jmMostrarTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMostrarTextoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmMostrarTexto);

        jMenu1.setText("Informacio");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        textAreaEditor.setEditable(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jmMostrarTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMostrarTextoMouseClicked
        controladorSintactico.escritura();
    }//GEN-LAST:event_jmMostrarTextoMouseClicked

    /**
     * @param args the command line arguments
     */

    public JTextArea getTextAreaEditor() {
        return textAreaEditor;
    }

    public void setTextAreaEditor(JTextArea textAreaEditor) {
        this.textAreaEditor = textAreaEditor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmGuardar;
    private javax.swing.JMenu jmGuardarComo;
    private javax.swing.JMenu jmMostrarTexto;
    private javax.swing.JTextArea textAreaEditor;
    // End of variables declaration//GEN-END:variables
}



